name: docorganizer
description: "Intuitive document-scanning app that enables users to easily scan, store, and manage documents directly from their mobile devices."
publish_to: 'none'
version: 1.1.0+110

environment:
  sdk: ">=3.7.2"
  flutter: ">=3.29.3"

dependencies:
  flutter:
    sdk: flutter
  
  # MLKit Document Scanner
  mlkit_document_scanner: ^0.0.10

  # Local persistence
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1

  # Sharing
  share_plus: ^10.1.4

  # Internationalization
  intl: ^0.20.2

  # PDF Viewer
  syncfusion_flutter_pdfviewer: ^29.1.38

  # Utilities
  simplest_logger: ^1.0.3
  simplest_service_locator: ^2.0.1

dev_dependencies:
  # Linter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

  # Testing
  flutter_test:
    sdk: flutter
  
flutter:
  uses-material-design: true
